### ISSUE TITLE
Certain mobs do not spawn

### ISSUE THREAD

**Issue by cybercat5555** [TeamTwilight/twilightforest-fabric#112]
### Fabric Loader Version

0.14.8

### Fabric API Version

fabric-api-0.58.0+1.18.2

### Twilight Forest Version

twilightforest-fabric-1.18.2-4.1.238

### Client Log

n/a

### Crash Report (if applicable)

n/a

### Steps to Reproduce

1. Enter a Dark Forest or Snowy biome
2. Mist Wolves, King Spiders, and Snow Wolves do not spawn

### What You Expected

That Mist Wolves, King Spiders, and Snow Wolves would spawn

### What Happened Instead

Those mobs do not spawn

### Additional Details

It is also possible some other mobs of this nature may not spawn,  as in "surface monsters". Though ones that spawn naturally in caves (i.e. Kobolds and vanilla Zombies), structures (i.e. Minotaurs), or from spawners (i.e. skeleton druids in their houses) spawn just fine. However even at that, mobs seem to be incredibly rare to spawn in Ghast Towers. However normal animals like Deer do spawn just fine on the surface.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
This isn't a fabric only issue, this is something that's been bugged since 1.16 and was fixed in 1.19. I provided an explanation as to why it happens on discord, but I'll post the conversation here too:

![image](https://user-images.githubusercontent.com/67468252/184672690-b31db353-bcb6-4f5f-9e24-b4dbbc41ea9c.png)

Closing as this has been resolved in forge 1.19. Fabric will also have it solved once its ports over.
