### ISSUE TITLE
Bug with REI

### ISSUE THREAD

**Issue by yahi-ko** [TeamTwilight/twilightforest-fabric#123]
### Fabric Loader Version

0.14.9

### Fabric API Version

0.62.0+1.19.2

### Twilight Forest Version

4.2.299

### Steps to Reproduce

Install REI 9.1.550 + The Twilight Forest 4.2.299

"Warnings during Roughly Enough Items initialization"

Minecraft can be played with both of the mod when it is on client but when both of it is on the server, it crashes

### What You Expected

Working with roughly enough items

### What Happened Instead

Crashing when REI and Twilight Forest is installed

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AlphaMode** [comment]
REI support is going to be discontinued for 1.20 I suggest you use JEI for now. Also you didn't provide a log so I can't help you

**Comment by omichaelv** [comment]
I got this bug on my server. THis is the log: "Rerached side issue when loading REI plugin by The Twilight Forest. Please use "rei_server", "rei_client" or "rei_common" instead"

"[Server] [INFO] java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'roughlyenoughitems'!
03.10 02:09:52 [Server] [INFO] at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.9.jar:?]
03.10 02:09:52 [Server] [INFO] at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.9.jar:?]
03.10 02:09:52 [Server] [INFO] at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.9.jar:?]
03.10 02:09:52 [Server] [INFO] at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.9.jar:?]
03.10 02:09:52 [Server] [INFO] at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.9.jar:?]
03.10 02:09:52 [Server] [INFO] at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
03.10 02:09:52 [Server] [INFO] at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
03.10 02:09:52 [Server] [INFO] at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
03.10 02:09:52 [Server] [INFO] at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
03.10 02:09:52 [Server] [INFO] at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
03.10 02:09:52 [Server] [INFO] Caused by: java.lang.RuntimeException: Failed to initialize REI entry point: me.shedaniel.rei.RoughlyEnoughItemsCore
03.10 02:09:52 [Server] [INFO] at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:88) ~[RoughlyEnoughItems-9.1.546.jar:?]
03.10 02:09:52 [Server] [INFO] at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:48) ~[RoughlyEnoughItems-9.1.546.jar:?]
03.10 02:09:52 [Server] [INFO] at java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:194) ~[?:?]
03.10 02:09:52 [Server] [INFO] at com.sun.proxy.jdk.proxy3.$Proxy35.onInitialize(Unknown Source) ~[?:?]
03.10 02:09:52 [Server] [INFO] at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.9.jar:?]
03.10 02:09:52 [Server] [INFO] ... 7 more
03.10 02:09:53 [Server] [INFO] Caused by: java.lang.RuntimeException: Rerached side issue when loading REI plugin by The Twilight Forest. Please use "rei_server", "rei_client" or "rei_common" instead.
03.10 02:09:53 [Server] [INFO] at me.shedaniel.rei.RoughlyEnoughItemsState.error(RoughlyEnoughItemsState.java:52) ~[RoughlyEnoughItems-9.1.546.jar:?]
03.10 02:09:53 [Server] [INFO] at me.shedaniel.rei.fabric.PluginDetectorImpl.loadPlugin(PluginDetectorImpl.java:108) ~[RoughlyEnoughItems-9.1.546.jar:?]
03.10 02:09:53 [Server] [INFO] at me.shedaniel.rei.fabric.PluginDetectorImpl.detectCommonPlugins(PluginDetectorImpl.java:139) ~[RoughlyEnoughItems-9.1.546.jar:?]
03.10 02:09:53 [Server] [INFO] at me.shedaniel.rei.RoughlyEnoughItemsCore.onInitialize(RoughlyEnoughItemsCore.java:135) ~[RoughlyEnoughItems-9.1.546.jar:?]
03.10 02:09:53 [Server] [INFO] at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:84) ~[RoughlyEnoughItems-9.1.546.jar:?]
03.10 02:09:53 [Server] [INFO] at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:48) ~[RoughlyEnoughItems-9.1.546.jar:?]
03.10 02:09:53 [Server] [INFO] at java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:194) ~[?:?]
03.10 02:09:53 [Server] [INFO] at com.sun.proxy.jdk.proxy3.$Proxy35.onInitialize(Unknown Source) ~[?:?]
03.10 02:09:53 [Server] [INFO] at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.9.jar:?]
03.10 02:09:53 [Server] [INFO] ... 7 more"

**Comment by AlphaMode** [comment]
This has been fixed
