### ISSUE TITLE
[Suggestion] Config to disable uncrafting table EMI support.

### ISSUE THREAD

**Issue by AmyMialee** [TeamTwilight/twilightforest-fabric#128]
### The Suggestion

As per title, an option to disable the EMI support for the uncrafting table.

### Why Should It Be in the Mod?

The uncrafting table has essentially every crafting table recipe in reverse, which makes almost all items have a recipe tab. It ends up being quite spammy and annoying.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by AmyMialee** [comment]
Also it's missing a lang title.

**Comment by LemmaEOF** [comment]
The uncrafting table's just a huge mess right now. Here's what comes up when I try to view a recipe tree for a very basic item in a pack I threw together: 
![image](https://user-images.githubusercontent.com/6722691/202311746-ac7f2cdb-35ea-4926-84b7-2a097092b407.png)

From what I can tell with EMI dev mode, this is because **the uncrafting table registers uncrafting recipes with the same ID as the normal version of the recipe**. This is very undesirable, and should probably be adjusted to add `_uncrafting` to the end of every recipe ID it generates.

**Comment by TropheusJ** [comment]
EMI compat is either going to be fixed or temporarily removed
