### ISSUE TITLE
"shipping outdated structure files" crash

### ISSUE THREAD

**Issue by dizzydizzee** [TeamTwilight/twilightforest-fabric#203]
### Fabric Loader Version

0.14.21

### Fabric API Version

0.76.0

### Twilight Forest Version

4.2.357

### Client Log

https://paste.ee/p/ltvks

### Steps to Reproduce

1. Run BetterMC modpack 1,19,2
2. Enter Twilight forest portal
3. move around a bit and game crashes

### What You Expected

to play without crashes

### What Happened Instead

the game crashed

### Additional Details

in the log at 22:56:38 "Mod twilightforest is shipping outdated structure files, which can cause worldgen lag; please report this to them." 
 I'm aware my crashing issue is more to do with memory (but annoying i dedicated 8gb to this instance!) but thought it was worth uploading this in case it's important - sorry I'm not that savvy with coding and modding

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
that message is unimportant, and will probably be fixed when structures are reworked on forge.
Your crash is caused by a series of OpenGL errors followed by a full JVM crash.
The error is `GL_OUT_OF_MEMORY`, so it seems you're out of GPU memory, not normal RAM. That's not something you can just allocate more of.
I can pretty much guarantee this crash has nothing to do with TF.
